FilmFair/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('accounts.urls')),
    path('', include(('main.urls', 'main'), namespace='main')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/<int:id>', views.movies, name='movies'),
    path('seat/<int:id>', views.seat, name='seat'),
    path('booked', views.booked, name='booked'),
    path('ticket/<int:id>', views.ticket, name='ticket'),
    path('booked_ticket/<int:pk>/', views.booked_ticket, name='booked_ticket'),

    # ――― Stripe checkout ―――
    path('checkout/', views.checkout_page, name='checkout_page'),
    path('create-session/', views.create_checkout_session, name='create_checkout_session'),
    path('success/', views.checkout_success, name='checkout_success'),
    path('cancel/', views.checkout_cancel, name='checkout_cancel'),

    # ――― NEW  invoice endpoints ―――
    path('invoice/<int:id>/',        views.invoice_view, name='invoice'),
    path('invoice/<int:id>/pdf/',    views.invoice_pdf,  name='invoice_pdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_shows.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>BoxOffice | Profile</title>
{% endblock %}

{% block style %}
<style>
    #wrapper {
        display: flex;
        margin-top: -62px;
    }

    .sidebar {
        width: 19rem !important;
        background: linear-gradient(0deg, #2196F3, #00106b);
        padding-top: 80px;
    }

    #content-wrapper {
        background-color: #e6e6e6;
        width: 100%;
        height: 100vh;
        padding-top: 60px;
        overflow-x: hidden;
    }

    .active {
        background: white;
        box-shadow: -1px 1px 13px 2px;
    }

    .nav-item:hover {
        background: #e0e0e0;
        box-shadow: -1px 1px 13px 2px;
    }

    .active-link,
    .nav-link:hover {
        color: #021045;
        display: block;
        padding: .5rem 0rem;
    }

    .nav-item {
        padding: 0px 20px;
        border-radius: 10px;
        margin: 5px 5px;
    }

    .nav-item a {
        font-size: 19px;
        font-weight: 500;
        text-decoration: none;
        color: #021045;
    }

    a.nav-link {
        color: white;
    }

    i {
        padding-right: 5px;
    }

    .round {
        padding: 20px;
        border-radius: 20px;
        min-height: 250px;
    }

    .poster {
        margin: 15px;

    }
</style>
{% endblock %}

{% block content %}


<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav sidebar ">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">
                <i class="fa fa-tachometer"></i>
                <span>Dashboard</span></a>
        </li>

        <li class="nav-item active">
            <a class="active-link" href="{% url 'add_shows' %}">
                <i class="fa fa-ticket"></i>
                <span>Add Shows</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'earnings' %}">
                <i class="fas fa-rupee-sign    "></i>
                <span>Earnings</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fa fa-sign-out"></i>
                <span>Logout</span></a>
        </li>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <div class="row m-3">
            <div class="col-12 card round">
                <h5 class="display-4">Add Shows at {{user.cinema.cinema_name}}</h5>
                <hr>


                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}

                <div class="row p-4">
                    <div class="col-12">
                        <form action="{% url 'add_shows' %}" method="POST">
                                {% csrf_token %}
                            <div class="form-row justify-content-center">
                                <div class="col-5">
                                    <select id="inputState" class="form-control" name="m">
                                        <option>Choose Movie</option>
                                        {% for list in mov %}
                                        <option value="{{list.movie}}">{{ list.movie_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-3">
                                    <input type="date" class="form-control" placeholder="Date" name="d">
                                </div>
                                <div class="col-2">
                                    <input type="time" class="form-control" placeholder="Time" name="t">
                                </div>
                                <div class="col-2">
                                    <input type="text" class="form-control" placeholder="Ticket Price (Rs)" name="p">
                                </div>
                            </div>
                            <div class="col-3 mt-4">
                                <input type="submit" class="btn btn-block btn-primary">
                            </div>
                    </div>
                    </form>
                </div>

                {% for movie in list %}
                <div class="col-3 poster p-0 shadow card text-center">
                    <img src="/media/{{movie.movie__movie_poster}}" class="img-fluid" alt="Misisng Poster">
                    <h5 class="p-3">{{movie.movie__movie_name}}</h5>
                </div>
                {% endfor %}
            </div>


            <div class="col-12 card round mt-2">
                    <h3 class="">All Shows at {{user.cinema.cinema_name}}</h3>
                    <hr>
                
                    <table class="table shadow text-center">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col" width="5%">ID</th>
                                    <th scope="col">Movie</th>
                                    <th scope="col">Time</th>
                                    <th scope="col">Date (YYYY/MM/DD)</th>
                                    <th scope="col">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for list in s %}
                                    <tr>
                                        <th scope="row">{{list.shows}}</th>
                                        <td>{{list.movie.movie_name}}</td>
                                        <td>{{list.time}}</td>
                                        <td>{{list.date}}</td>
                                        <td>Rs. {{list.price}}</td>
                                    </tr>
                                        {% endfor %}
                            </tbody>
                        </table>
                    
                </div>

        </div>
    </div>
</div>
<!-- End of Content Wrapper -->

</div>



{% endblock %}


{% block JQuery %}
<script>
</script>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% block title%}{% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <script src="https://kit.fontawesome.com/7dd9aac670.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "styles/main.css" %}>
    {% block style %}{% endblock %}

    <style>
            .search-text {
                border-radius: 30px 0px 0px 30px;
            }
    
            .search {
                border-radius: 0px 30px 30px 0px;
                width: 45px;
                color: white;
                background: linear-gradient(45deg, #ef2c3f, #dc3545);
            }
    </style>    

</head>
  <body>
      
    <nav class="navbar sticky-top" style="background-color: #0000006b">
        <div class="col-lg-3 col-md-4 col-8">
            <h2 class="text-white"> <a role="button" href={% url 'index' %} style="text-decoration: none; color: white;" ><i class="fa fa-video-camera"></i>FilmFair</a></h2>
        </div>
        <div class="col-lg-5 col-4 d-none d-md-inline">
                <form class="row" action="#" method="GET">
                    <div class="input-group col-12">
                        <input type="search" class="form-control search-text" placeholder="Search Movies">
                        <button type="submit" class="btn search"><i class="fa fa-search" aria-hidden="true"></i></button>
                    </div>
                </form>
        </div>
        {% if user.is_authenticated %}
        <div class="col-lg-3 col-4">
                <div class="dropdown">
                        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fa fa-user" aria-hidden="true"></i> {{user.first_name }}
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            {% if user.cinema.role == 'cinema_manager' %}
                            <a class="dropdown-item" href="{% url 'dashboard' %}"> <i class="fa fa-edit"></i> Dashboard</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'profile' %}"> <i class="fa fa-edit"></i> Profile</a>
                            <a class="dropdown-item" href="{% url 'bookings' %}"> <i class="fa fa-ticket"></i> Bookings</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                        </div>
                </div>
        </div>
        {%  else  %}
        <div class="col-lg-3 col-12 mt-2">
            <div class="row no-gutters">
                <div class="col mr-1">
                    <a class="btn btn-danger d-block" href="{% url 'register' %}" role="button"> Sign Up </a>
                </div>
                <div class="col">
                    <a class="btn btn-danger d-block" href="{% url 'login' %}" role="button"> Sign In </a> 
                </div>
            </div>    
        </div>
        {% endif %}
    </nav>

    {% block content %}
    {% endblock %}
    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    

    {% block JQuery %}
    {% endblock %}

</body>
</html>

templates/booked_ticket.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>BoxOffice</title>
{% endblock %}

{% block style %}
<style>
  body {
    background: #2196f34a;
  }

  .title {
    padding: 10px;
    color: white;
    text-decoration: none;
  }

  .card {
    margin: 100px auto;
    border-radius: 10px;
    border: none;
  }

  .pass-h {
    border-radius: 10px 10px 0px 0px;
    background: linear-gradient(45deg, red, #ff4343);
  }

  .info {
    line-height: 40px;
    background: #000;
    color: white;
    font-size: 20px;
    border: solid 1px;
    border-right: 0px;
    border-radius: 50px 0px 0px 50px;
  }

  h3 span {
    font-weight: 400;
  }

  .btn-print {
    padding: 10px 20px;
    font-size: 18px;
    font-weight: bold;
    border-radius: 8px;
    transition: background-color 0.3s ease;
    background-color: #007bff;
    color: white;
    border: none;
  }

  .btn-print:hover {
    background-color: #0056b3;
  }

  @media print {
    .btn-print, nav, footer {
      display: none !important;
    }
    body {
      background: white !important;
    }
    .card {
      box-shadow: none !important;
    }
  }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 card shadow">
      <div class="row justify-content-around pass-h title">
        <div class="col-4">
          <h2><i class="fa fa-video-camera"></i> BoxOffice</h2>
        </div>
        <div class="col-6">
          <h2 style="text-align:center">{{ticket.shows.movie.movie_name}} ({{ticket.shows.cinema.cinema_name}})</h2>
        </div>
      </div>

      <div class="row mt-4 mb-4">
        <div class="col-3">
          <img class="img-fluid shadow-sm border" src="{{ ticket.shows.movie.movie_poster.url }}">
        </div>
        <div class="col-9">
          <div class="row">
            <div class="col-6">
              <h3>Booking ID: <span>{{ticket.pk}}</span></h3>
              <h3>Date: <span>{{ticket.shows.date}}</span></h3>
              <h3>Price: <span>₹{{ total_price }}</span></h3>
            </div>
            <div class="col-6">
              <h3>Seats: <span>{{ticket.useat}}</span></h3>
              <h3>Time: <span>{{ticket.shows.time}}</span></h3>
              <h3>Hall: <span>H1</span></h3>
            </div>
            <div class="col-12 mt-3 info">
              <i class="fa fa-location-arrow"></i> {{ticket.shows.cinema.cinema_name}}: <span>{{ticket.shows.cinema.address}}</span>
            </div>
          </div>
        </div>

        <div class="col-12 d-flex justify-content-end mt-3">
          <button class="btn btn-print" onclick="window.print()">
            <i class="fa fa-print"></i> Print Ticket
          </button>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/bookings.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>BoxOffice | Bookings</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href={% static "styles/bookings.css" %} />
{% endblock %}

{% block content %}
<div class="container-fluid box">
  <div class="row justify-content-center">
    <div class="col-8 card p-2 shadow mt-5">
      <table class="table text-center">
        <thead class="thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Movie Name</th>
            <th scope="col">Cinema</th>
            <th scope="col">Show Date</th>
            <th scope="col">Total&nbsp;Price</th>
            <th scope="col">View</th>
          </tr>
        </thead>
        <tbody>
          {% for b in book %}
          <tr>
            <td>{{ b.pk }}</td>
            <td>{{ b.shows.movie.movie_name }}</td>
            <td>{{ b.shows.cinema.cinema_name }}</td>
            <td>{{ b.shows.date }}</td>
            <td>₹{{ b.total_price }}</td>
            <td>
              <a
                class="btn submit"
                href="{% url 'booked_ticket' b.pk %}"
                target="_blank"
                >View&nbsp;Ticket</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

templates/cancel.html
<!DOCTYPE html>
<html>
  <body>
    <h1>⚠️ Payment canceled</h1>
    <p><a href="{% url 'main:checkout_page' %}">Try again</a></p>
  </body>
</html>

templates/checkout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Buy Ticket</title>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <h2>Pay for your ticket</h2>
    <form action="{% url 'create_checkout_session' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Checkout</button>
    </form>

    
    </form>
  </body>
</html>

templates/error.html
<!-- templates/error.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    <h1>Something went wrong</h1>
    <p>{{ message }}</p>
    <a href="{% url 'index' %}">Back to Home</a>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>FilmFair | Home</title>
{% endblock %}

{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="s1"></div>
        </div>
        <div class="carousel-item">
            <div class="s2"></div>
        </div>
        <div class="carousel-item">
            <div class="s3"></div>
        </div>
        <div class="carousel-item">
            <div class="s4"></div>
        </div>
        <div class="carousel-item">
            <div class="s5"></div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container">
    <div class="row mb-5">
        <div class="col-12">
            <div class="row">
                <div class="col-10 offset-2 m-5">
                    <h1>Now Showcasing</h1>
                </div>
            </div>
            <div class="row">

                {% for movie in mov %}
                <div class="col-12 col-md-6 col-lg-4 mb-5">
                    <a href="/movies/{{movie.pk}}">
                        <div class="card shadow" style="width: 18rem; margin:0px auto;">
                            <img src="{{ movie.movie_poster.url }}" class="card-img-top" height="380px">
                            <div class="card-body">
                                <h4 class="card-title text-center">{{ movie.movie_name }}</h4>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>BoxOffice | Home</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href={% static "styles/login.css" %} />
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-end">
        <div class="col-md-5 col-10 login">
            <form action="login" method="POST" class="text-white">
                {% csrf_token %}
                <h1>Login</h1>
                <div class="form-group">
                    <label class="form-label">Username</label>
                    <input class="form-control" type="text" name="username" placeholder="username">
                </div>
                <div class="form-group">
                    <label class="form-label">Password</label>
                    <input class="form-control" type="password" name="password" placeholder="password">
                </div>
                <input class="btn btn-primary btn-lg" type="submit" value="Login">
            </form>
        </div>
    </div>
</div>


{% for message in messages%}
<h4>{{ message }}</h4>
{% endfor %}


{% endblock %}

templates/movies.html
{% extends 'base.html' %}

{% block title %}
<title>BoxOffice | {{movies.movie_name}}</title>
{% endblock %}

{% block style %}
<style>
    .bg {
        background: linear-gradient(to right, rgba(138, 181, 206, 0), #000),
        url({{movies.movie_poster.url}});
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        width: 100%;
        height: 100vh;
    }

    .bl {
        background: black;
    }

    .right-c {
        margin-top: 150px;
        color: #fff;
    }

    .pillow {
        background: rgba(0, 0, 0, 0.13);
        border-radius: 50px;
        color: white;
        border: solid 1px whitesmoke;
        padding: 5px 10px;
        text-align: center;
        width: 60%;
    }

    .title {
        font-size: 50px;
        padding: 10px 0px;
    }

    .rate {
        margin: 10px 0px;
        margin-left: 30px;
    }

    .rate i {
        text-shadow: 0 0 5px white;
        color: red;
    }

    .desc {
        margin: 5px 50px 5px 5px;
    }

    .btn-custom {
        background: linear-gradient(320deg, blue, red);
        color: #fff;
        border: none;
        border-radius: 10px;
        width: 230px;
        margin: 5px;
    }

    .btn-custom i {
        padding: 0px 5px;
    }

    .btn-custom:hover {
        color: #fff;
        border: solid 2px white;
        background: transparent;
    }

    .time {
        margin: 5px;
        display: inline;
    }
</style>

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row" style="margin-top: -63px">
        <div class="col-7 bg">

        </div>
        <div class="col-5 bl">
            <div class="row">
                <div class="col-12 right-c">
                    <h1 class="title">{{movies.movie_name}}</h1>
                    <h4 class="pillow">{{movies.movie_genre}}</h4>
                    <h4 style="padding: 5px 0px"> <i class="fa fa-clock-o" aria-hidden="true"></i>
                        {{movies.movie_duration}} | <i class="fa fa-calendar-o"></i> {{movies.movie_rdate}} </h4>
                    <p class="desc">{{movies.movie_des}}</p>
                    <h1 class="rate"> <i class="fa fa-heart"></i> {{movies.movie_rating}} </h1>
                    <button type="button" id="btn-t" class="btn btn-lg btn-custom">Watch Trailer <i
                            class="fa fa-play-circle"></i>
                    </button>
                    <button type="button" id="btn-time" class="btn btn-lg btn-custom">Book Now <i
                            class="fa fa-ticket"></i> </button>
                              

                </div>

                <div class="modal fade" id="trailer" tabindex="-1">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <!-- <iframe width="800px" height="500px" src="{{movies.movie_trailer}}"
                                allowfullscreen></iframe> -->
                                <iframe
                                width="800"
                                height="500"
                                src="{{ movies.trailer_embed_url }}"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                              </iframe>
                              
                        </div>
                    </div>
                </div>


                <!-- Modal for time selection-->
                <div class="modal fade" id="shows" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title"> Select cinema and timings </h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid">


                                    {% for i in cin %}
                                    <div class="row">
                                        <div class="col-12">
                                            <h3>{{i.cinema_name}}</h3>
                                        </div>
                                        <div class="col-12 mb-4">
                                            {% for j in i.cinema_show.all %}
                                            {% if j.movie_id == movies.movie %}
                                            <h5 class="time"><a href="/seat/{{j.shows}}"
                                                    class="badge badge-primary">{{j.time}}</a></h5>
                                            {% endif %}
                                            {% endfor %}
                                        </div>  
                                    </div>
                                    {% endfor %}

                                    
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>



    <div class="container d-none">
        <div class="row mt-5">
            <div class="col-3">
                <div class="card">
                    <img class="card-img-top" src="{{movies.movie_poster.url}}" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title">{{movies.movie_name}}</h4>
                        <p class="card-text">{{movies.movie_rating}}</p>

                    </div>
                </div>
            </div>

            <div class="col-6">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Cinema</th>
                            <th>Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            {% for i in cin %}
                            <td scope="row"> {{i.cinema_name}} </td>
                            {% for j in i.cinema_show.all %}

                            {% if j.movie_id == movies.movie %}
                            <td><a href="/seat/{{j.shows}}"> {{j.time}} </a></td>
                            {% endif %}

                            {% endfor %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% endblock %}


    {% block JQuery %}

    <script>
        $('#btn-t').click(function () {
            $('#trailer').modal('toggle')
        });

        $('#btn-time').click(function () {
            $('#shows').modal('toggle')
        });
         // 🔧 Stop trailer video when modal is closed
        $('#trailer').on('hidden.bs.modal', function () {
            var iframe = $(this).find('iframe');
            var src = iframe.attr('src');
            iframe.attr('src', '');
            iframe.attr('src', src);
        });
    </script>

    {% endblock %}

templates/ticket.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>BoxOffice</title>
{% endblock %}

{% block style %}
<style>
  body {
    background: #2196f34a;
  }

  .title {
    padding: 10px;
    color: white;
    text-decoration: none;
  }

  .card {
    margin: 100px auto;
    border-radius: 10px;
    border: none;
  }

  .pass-h {
    border-radius: 10px 10px 0px 0px;
    background: linear-gradient(45deg, red, #ff4343);
}

  .info {
    line-height: 40px;
    background: #000;
    color: white;
    font-size: 20px;
    border: solid 1px;
    border-right: 0px;
    border-radius: 50px 0px 0px 50px;
  }

  h3 span {
    font-weight: 400;
  }
  .checkout-btn {
    padding: 10px 20px;
    font-size: 18px;
    font-weight: bold;
    border-radius: 8px;
    transition: background-color 0.3s ease;
    background-color: #b12e2e; /* Bootstrap success color */
    color: white;
    border: none;
  }

  .checkout-btn:hover {
    background-color: #45a045	;
    color: white;
  }

  .checkout-form {
    margin-right: 10px;
  }
</style>
{% endblock %}


{% block content %}

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8 card shadow">
      <div class="row justify-content-around pass-h title">
        <div class="col-4">
          <h2> <i class="fa fa-video-camera"></i> BoxOffice</h2>
        </div>
        <div class="col-6">
          <h2 style="text-align:center">{{ticket.shows.movie.movie_name}} ({{ticket.shows.cinema.cinema_name}})</h2>
        </div>
      </div>
      <div class="row mt-4 mb-4">
        <div class="col-3">
          <img class="img-fluid shadow-sm border" src="{{ ticket.shows.movie.movie_poster.url }}">

        </div>
        <div class="col-9">
          <div class="row">
            <div class="col-6">
              <h3>Booking ID :<span> {{ticket.pk}}</span> </h3>
              <h3>Date :<span> {{ticket.shows.date}}</span> </h3>
              <h3>Price :<span> ₹{{ total_price }}</span> </h3>
            </div>
            <div class="col-6">
              <h3>Seats :<span> {{ticket.useat}}</span> </h3>
              <h3>Time :<span> {{ticket.shows.time}}</span> </h3>
              <h3>Hall :<span> H1</span> </h3>
            </div>
            <div class="col-12 mt-3 info">
               <i class="fa fa-location-arrow"></i> {{ticket.shows.cinema.cinema_name}} : <span> {{ticket.shows.cinema.address}}</span>
            </div>
          </div>
        </div>
        <div class="col-12 d-flex justify-content-end mt-3">
          <form action="{% url 'create_checkout_session' %}" method="POST" class="checkout-form">
            {% csrf_token %}
            <input type="hidden" name="ticket_id" value="{{ ticket.pk }}">
            <button type="submit" class="btn btn-success checkout-btn">
              Proceed to Pay ₹{{ total_price }}
            </button>
            
          </form>
        </div>
    
      </div>
    </div>
  </div>


  {% endblock %}